import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/custom/app-sidebar";
import AppSidebarProvider from "@/components/sidebar-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { PageLayoutHeader } from "@/components/custom/page-layout";
import CustomBreadcrumb from "@/components/custom/custom-breadcrumb";
import NotificationPopover from "@/components/custom/notification-popover";
import { ThemeModeToggle } from "@/components/custom/theme-toggle";
import ProfileDropdown from "@/components/custom/profile-dropdown";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <AppSidebarProvider>
          <AppSidebar />
          <main className="relative w-full h-screen overflow-x-hidden">
              <PageLayoutHeader className="sticky top-0 z-10">
                <CustomBreadcrumb />
                <div className="flex items-center">
                  <NotificationPopover />
                  <ThemeModeToggle />
                  <ProfileDropdown className="ml-1" />
                </div>
              </PageLayoutHeader>
              {children}
          </main>
        </AppSidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
